name: Build JVM Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Check Details
        run: |
          echo "⏰Trigger at `date "+%Y-%m-%d %H:%M:%S"`"
          echo "💡Build image with ${{ github.ref_name }}"
          ./mvnw -v
          free -h

      - name: Build Image
        run: |
          ./mvnw package \
            -Dquarkus.container-image.image="${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:${{ github.ref_name }}" \
            -Dquarkus.container-image.build=true

      - name: Image Alias
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:${{ github.ref_name }} ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:latest

      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:latest
