name: Native Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Check Details
        run: |
          echo "⏰Trigger at `date +%Y%m%d%H%M%S`"
          echo "💡Build image with ${{ github.ref_name }}"
          ./mvnw -v

      - name: Build Native runner
        run: |
          ./mvnw package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true

      - name: Build Docker Image
        run: |
          docker build -f src/main/docker/Dockerfile.native-micro -t ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:latest -t ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:${{ github.ref_name }} .

      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ezpie-simple-app:latest
